spring.application.name=oceanview

spring.data.mongodb.uri=mongodb+srv://velis:kxyoFfcWmFa8o2X9@ocenview.t3bgwso.mongodb.net/
spring.data.mongodb.database=oceanview_db

server.port=8080

app.jwt.secret=OceanViewResortSecretKey2025CIS6003AdvancedProgrammingCardiffMet
app.jwt.expiration=86400000

app.cors.allowed-origins=http://localhost:5173

logging.level.com.oceanview=DEBUG